### ISSUE TITLE
Store classic mode deprecated

### ISSUE THREAD

**Issue by smnscp** [vuex-orm/vuex-orm-examples-nuxt#1] opened 2019-02-26 14:39 UTC
Since the Vuex store is configured in [classic mode](https://nuxtjs.org/guide/vuex-store#classic-mode) we get a warning in the console saying “Classic mode for store/ is deprecated and will be removed in Nuxt 3.”
We should adjust store/index.js to use modules mode and [export plugins](https://nuxtjs.org/guide/vuex-store#plugins).

**Comment by ml-haivx** [comment] 2019-02-27 07:11
I'm also having trouble implementing Vue-orm with Modules mode. Would you be able to provide a sample?

**Comment by smnscp** [comment] 2019-02-27 09:11
Hi @ml-haivx, please take a look at my pull request #2. You can just apply these changes in your project and it should work.

**Comment by kiaking** [comment] 2019-04-04 12:26
Sorry it took so long but the issue is resolved by #2! Thanks to @smnscp 👍

**Closed by kiaking** 2019-04-04 12:26 UTC
